"""
Round 6 — Cross-round integration tests for packaging & release system.

Validates that all components from Rounds 1-5 work together correctly:
- Packaging scripts reference correct paths matching nfpm contents
- CLI wizard generates configs compatible with packaging expectations
- Web wizard endpoints use the same config builder as CLI wizard
- Auth bypass works for setup endpoints
- Workflow references match packaging file locations
- postinstall port matches actual web server port config
"""
from __future__ import annotations

import copy
import os
import stat
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import yaml

from src.packaging.validate import (
    DATA_SUBDIRS,
    FHS_PATHS,
    REQUIRED_CONTENT_DESTINATIONS,
    REQUIRED_DEB_DEPENDS,
    REQUIRED_SERVICE_DIRECTIVES,
    check_script_syntax,
    extract_script_operations,
    parse_nfpm_config,
    parse_systemd_unit,
    parse_workflow,
    validate_nfpm_config,
    validate_nfpm_file_references,
    validate_postinstall,
    validate_preremove,
    validate_release_workflow,
    validate_service_file,
    validate_workflow_actions,
)
from src.setup_wizard import (
    _DEFAULT_CONFIG,
    SetupWizard,
    build_config,
    build_env,
    is_setup_needed,
    validate_token_format,
)

PACKAGING_DIR = Path(__file__).parent.parent / "packaging"
WORKFLOWS_DIR = Path(__file__).parent.parent / ".github" / "workflows"
UI_DIR = Path(__file__).parent.parent / "ui"
SRC_DIR = Path(__file__).parent.parent / "src"


# ===================================================================
# Cross-round: Packaging ↔ CLI Wizard consistency
# ===================================================================


class TestPackagingWizardConsistency:
    """Verify packaging scripts and CLI wizard are consistent."""

    def test_postinstall_wizard_path_references_setup_module(self):
        """postinstall.sh references the correct Python module for setup."""
        content = (PACKAGING_DIR / "postinstall.sh").read_text()
        assert "src.setup" in content, \
            "postinstall must reference 'src.setup' module for wizard"

    def test_postinstall_port_matches_config_default(self):
        """postinstall.sh web wizard URL port matches config schema default."""
        from src.config.schema import WebConfig
        default_port = WebConfig.model_fields["port"].default

        content = (PACKAGING_DIR / "postinstall.sh").read_text()
        assert f"localhost:{default_port}" in content, \
            f"postinstall must reference port {default_port} (WebConfig default)"

    def test_wizard_config_sections_match_default_config(self):
        """Wizard _DEFAULT_CONFIG has same sections as build_config output."""
        cfg = build_config()
        for section in _DEFAULT_CONFIG:
            assert section in cfg, \
                f"build_config missing section from _DEFAULT_CONFIG: {section}"

    def test_wizard_generated_config_valid_yaml(self):
        """Config generated by wizard is valid YAML round-trip."""
        cfg = build_config(
            hosts={"srv": {"address": "10.0.0.1", "ssh_user": "root"}},
            features={"browser": True, "voice": False, "comfyui": False},
            web_api_token="test-token",
        )
        yaml_str = yaml.dump(cfg, default_flow_style=False, sort_keys=False)
        restored = yaml.safe_load(yaml_str)
        assert restored["discord"]["token"] == cfg["discord"]["token"]
        assert restored["tools"]["hosts"]["srv"]["address"] == "10.0.0.1"
        assert restored["browser"]["enabled"] is True

    def test_wizard_env_output_matches_postinstall_env_location(self):
        """Wizard generates .env that postinstall would place in /etc/heimdall/."""
        env_content = build_env("test.token.value")
        assert "DISCORD_TOKEN=test.token.value" in env_content
        # Verify format matches what postinstall copies from .env.example
        lines = env_content.strip().splitlines()
        for line in lines:
            if line.startswith("#") or not line.strip():
                continue
            assert "=" in line, f"Non-comment env line missing '=': {line}"

    def test_postinstall_creates_dirs_for_default_config_paths(self):
        """postinstall.sh creates directories referenced in _DEFAULT_CONFIG."""
        content = (PACKAGING_DIR / "postinstall.sh").read_text()
        ops = extract_script_operations(content)

        # _DEFAULT_CONFIG references ./data/sessions, ./data/context, etc.
        # postinstall creates these under /var/lib/heimdall/
        for subdir in DATA_SUBDIRS:
            assert any(subdir in line for line in ops["directory_creation"]), \
                f"postinstall must create data subdir '{subdir}'"


# ===================================================================
# Cross-round: nfpm ↔ Packaging scripts consistency
# ===================================================================


class TestNfpmScriptConsistency:
    """Verify nfpm config references valid packaging scripts."""

    def test_nfpm_postinstall_script_passes_bash_syntax(self):
        """postinstall.sh referenced by nfpm passes bash -n syntax check."""
        ok, err = check_script_syntax(PACKAGING_DIR / "postinstall.sh")
        assert ok, f"postinstall.sh syntax error: {err}"

    def test_nfpm_preremove_script_passes_bash_syntax(self):
        """preremove.sh referenced by nfpm passes bash -n syntax check."""
        ok, err = check_script_syntax(PACKAGING_DIR / "preremove.sh")
        assert ok, f"preremove.sh syntax error: {err}"

    def test_nfpm_scripts_are_executable(self):
        """Packaging scripts have executable permission."""
        for script in ("postinstall.sh", "preremove.sh"):
            path = PACKAGING_DIR / script
            mode = path.stat().st_mode
            assert mode & stat.S_IXUSR, f"{script} must be executable"

    def test_nfpm_content_sources_all_exist(self):
        """All source files referenced by nfpm.yml exist."""
        content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(content)
        errors = validate_nfpm_file_references(config, PACKAGING_DIR)
        assert errors == [], f"Missing nfpm content sources: {errors}"

    def test_nfpm_installs_setup_wizard_module(self):
        """nfpm.yml installs src/ which includes setup_wizard.py."""
        content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(content)
        dsts = [e.get("dst", "") for e in config.get("contents", [])]
        assert any("/opt/heimdall/src/" in d for d in dsts), \
            "nfpm must install src/ (contains setup_wizard.py)"

    def test_nfpm_installs_web_ui(self):
        """nfpm.yml installs ui/ which includes setup-wizard.js."""
        content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(content)
        dsts = [e.get("dst", "") for e in config.get("contents", [])]
        assert any("/opt/heimdall/ui/" in d for d in dsts), \
            "nfpm must install ui/ (contains setup-wizard.js)"


# ===================================================================
# Cross-round: Workflow ↔ nfpm consistency
# ===================================================================


class TestWorkflowNfpmConsistency:
    """Verify release workflow correctly references nfpm config."""

    def test_workflow_nfpm_config_path_matches_real_file(self):
        """Workflow uses config path that resolves to actual nfpm.yml."""
        workflow_content = (WORKFLOWS_DIR / "release.yml").read_text()
        nfpm_config = PACKAGING_DIR / "nfpm.yml"
        assert nfpm_config.exists(), "packaging/nfpm.yml must exist"
        assert "packaging/nfpm.yml" in workflow_content, \
            "Workflow must reference packaging/nfpm.yml"

    def test_workflow_version_extraction_format(self):
        """Workflow extracts version from tag in expected format."""
        workflow_content = (WORKFLOWS_DIR / "release.yml").read_text()
        # Should strip 'v' prefix from tag: v1.2.3 -> 1.2.3
        assert "GITHUB_REF_NAME#v" in workflow_content, \
            "Workflow must strip 'v' prefix from tag"

    def test_workflow_passes_version_to_nfpm(self):
        """Workflow passes VERSION env var to nfpm build step."""
        workflow_content = (WORKFLOWS_DIR / "release.yml").read_text()
        assert "VERSION" in workflow_content, \
            "Workflow must pass VERSION to nfpm"


# ===================================================================
# Cross-round: Web wizard ↔ CLI wizard shared logic
# ===================================================================


class TestWebCliWizardSharedLogic:
    """Verify web and CLI wizards share the same config generation logic."""

    def test_web_api_imports_from_setup_wizard(self):
        """api.py imports build_config, build_env from setup_wizard."""
        api_content = (SRC_DIR / "web" / "api.py").read_text()
        assert "from ..setup_wizard import" in api_content
        assert "build_config" in api_content
        assert "build_env" in api_content
        assert "is_setup_needed" in api_content
        assert "validate_token_format" in api_content

    def test_web_and_cli_build_config_produce_same_structure(self):
        """build_config with same args produces same structure regardless of caller."""
        hosts = {"srv": {"address": "10.0.0.1", "ssh_user": "deploy"}}
        features = {"browser": True, "voice": False, "comfyui": True}

        cfg = build_config(
            timezone="US/Eastern",
            hosts=hosts,
            features=features,
            web_api_token="tok123",
            claude_code_host="srv",
        )

        # All 16 sections present
        expected_sections = [
            "discord", "openai_codex", "context", "sessions", "tools",
            "webhook", "learning", "search", "logging", "usage",
            "voice", "browser", "monitoring", "permissions", "comfyui", "web",
        ]
        for section in expected_sections:
            assert section in cfg, f"Missing section: {section}"

        # Features applied
        assert cfg["browser"]["enabled"] is True
        assert cfg["voice"]["enabled"] is False
        assert cfg["comfyui"]["enabled"] is True

        # Hosts applied
        assert cfg["tools"]["hosts"]["srv"]["address"] == "10.0.0.1"
        assert cfg["tools"]["claude_code_host"] == "srv"
        assert cfg["web"]["api_token"] == "tok123"
        assert cfg["timezone"] == "US/Eastern"

    def test_build_env_produces_valid_env_format(self):
        """build_env output is parseable as env file."""
        content = build_env("test.token.value", extra={"EXTRA_VAR": "extra_val"})
        env_vars = {}
        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("#") or not stripped:
                continue
            key, _, val = stripped.partition("=")
            env_vars[key] = val

        assert env_vars["DISCORD_TOKEN"] == "test.token.value"
        assert env_vars["EXTRA_VAR"] == "extra_val"

    def test_is_setup_needed_shared_between_web_and_cli(self, tmp_path):
        """is_setup_needed function works for both web and CLI wizards."""
        config_path = tmp_path / "config.yml"
        env_path = tmp_path / ".env"

        # No files = setup needed
        assert is_setup_needed(config_path, env_path) is True

        # Create config but no env
        config_path.write_text("discord:\n  token: test\n")
        assert is_setup_needed(config_path, env_path) is True

        # Create env with real token
        env_path.write_text("DISCORD_TOKEN=real.token.here\n")
        assert is_setup_needed(config_path, env_path) is False


# ===================================================================
# Cross-round: Auth bypass ↔ Web wizard
# ===================================================================


class TestAuthBypassIntegration:
    """Verify auth bypass for setup endpoints is consistent."""

    def test_auth_skip_prefix_covers_both_setup_endpoints(self):
        """_AUTH_SKIP_API_PREFIXES covers status and complete endpoints."""
        from src.health.server import _AUTH_SKIP_API_PREFIXES

        status_path = "/api/setup/status"
        complete_path = "/api/setup/complete"

        assert any(status_path.startswith(p) for p in _AUTH_SKIP_API_PREFIXES), \
            f"{status_path} must match auth skip prefix"
        assert any(complete_path.startswith(p) for p in _AUTH_SKIP_API_PREFIXES), \
            f"{complete_path} must match auth skip prefix"

    def test_setup_route_excluded_from_sidebar(self):
        """Setup wizard page is excluded from sidebar navigation."""
        app_js = (UI_DIR / "js" / "app.js").read_text()
        # noSidebar meta must be set
        assert "noSidebar" in app_js
        # The nav filter uses meta.icon to exclude setup page (which has no icon)
        assert "r.meta.icon" in app_js or "meta.icon" in app_js

    def test_web_wizard_page_uses_raw_fetch_not_api(self):
        """Setup wizard page uses raw fetch() since auth isn't configured yet."""
        wizard_js = (UI_DIR / "js" / "pages" / "setup-wizard.js").read_text()
        assert "fetch('/api/setup/complete'" in wizard_js or \
               'fetch("/api/setup/complete"' in wizard_js, \
            "Wizard must use raw fetch() for API calls (not api._request)"


# ===================================================================
# Cross-round: Service file ↔ Packaging ↔ Config consistency
# ===================================================================


class TestServicePackagingConfigConsistency:
    """End-to-end consistency between service file, packaging, and config."""

    def test_service_working_directory_matches_nfpm_install_dir(self):
        """Service file WorkingDirectory matches nfpm install location."""
        service_content = (PACKAGING_DIR / "heimdall.service").read_text()
        parsed = parse_systemd_unit(service_content)
        work_dir = parsed["Service"]["WorkingDirectory"]

        nfpm_content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(nfpm_content)
        dsts = [e.get("dst", "") for e in config.get("contents", [])]

        # At least one nfpm content entry should install under WorkingDirectory
        assert any(d.startswith(work_dir) for d in dsts), \
            f"nfpm must install content under {work_dir}"

    def test_service_env_file_dir_matches_nfpm_dir_entry(self):
        """Service EnvironmentFile dir matches nfpm created directory."""
        service_content = (PACKAGING_DIR / "heimdall.service").read_text()
        parsed = parse_systemd_unit(service_content)
        env_file = parsed["Service"]["EnvironmentFile"]
        env_dir = str(Path(env_file).parent)

        nfpm_content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(nfpm_content)
        dir_dsts = [
            e.get("dst", "").rstrip("/")
            for e in config.get("contents", [])
            if isinstance(e, dict) and e.get("type") == "dir"
        ]

        assert env_dir in dir_dsts, \
            f"nfpm must create directory for {env_dir}"

    def test_service_readwrite_paths_match_nfpm_dirs(self):
        """Service ReadWritePaths matches nfpm-created directories."""
        service_content = (PACKAGING_DIR / "heimdall.service").read_text()
        parsed = parse_systemd_unit(service_content)
        rw_paths = parsed["Service"].get("ReadWritePaths", "").split()

        nfpm_content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(nfpm_content)
        dir_dsts = [
            e.get("dst", "").rstrip("/")
            for e in config.get("contents", [])
            if isinstance(e, dict) and e.get("type") == "dir"
        ]

        for rw in rw_paths:
            assert rw in dir_dsts, \
                f"ReadWritePath {rw} must match an nfpm dir entry"


# ===================================================================
# Cross-round: CLI wizard end-to-end with real file I/O
# ===================================================================


class TestCLIWizardEndToEnd:
    """End-to-end tests for the CLI wizard with real file I/O."""

    def test_wizard_writes_all_config_sections(self, tmp_path):
        """Full wizard run writes config with all 16 sections."""
        config_path = tmp_path / "config.yml"
        env_path = tmp_path / ".env"

        inputs = iter([
            "MTIz.NDU2.Nzg5",  # Discord token
            "n",                # Skip Codex auth
            "y", "webhost", "10.0.0.5", "deploy",  # Host
            "n",                # No more hosts
            "y", "y", "n",     # browser, voice, no comfyui
            "y",                # claude code
            "y",                # Generate web token
        ])

        wizard = SetupWizard(
            config_path=config_path,
            env_path=env_path,
            input_fn=lambda _: next(inputs),
            print_fn=lambda *a, **k: None,
        )

        async def _mock_validate(token):
            return (True, {"username": "Bot", "id": "1"})

        with patch("src.setup_wizard.validate_discord_token", _mock_validate):
            with patch("src.setup_wizard.detect_systemd", return_value=False):
                success = wizard.run()

        assert success is True
        assert config_path.exists()
        assert env_path.exists()

        data = yaml.safe_load(config_path.read_text())
        expected_sections = [
            "discord", "openai_codex", "context", "sessions", "tools",
            "webhook", "learning", "search", "logging", "usage",
            "voice", "browser", "monitoring", "permissions", "comfyui", "web",
        ]
        for section in expected_sections:
            assert section in data, f"Missing section: {section}"

        # Verify host and features
        assert data["tools"]["hosts"]["webhost"]["address"] == "10.0.0.5"
        assert data["tools"]["hosts"]["webhost"]["ssh_user"] == "deploy"
        assert data["browser"]["enabled"] is True
        assert data["voice"]["enabled"] is True
        assert data["comfyui"]["enabled"] is False
        assert data["tools"]["claude_code_host"] == "webhost"
        assert len(data["web"]["api_token"]) == 32

        # Verify env
        env = env_path.read_text()
        assert "DISCORD_TOKEN=MTIz.NDU2.Nzg5" in env

    def test_wizard_env_permissions_secure(self, tmp_path):
        """Wizard-generated .env has 0600 permissions."""
        config_path = tmp_path / "config.yml"
        env_path = tmp_path / ".env"

        inputs = iter([
            "MTIz.NDU2.Nzg5",
            "n", "n", "n", "n", "n", "n", "",
        ])

        wizard = SetupWizard(
            config_path=config_path,
            env_path=env_path,
            input_fn=lambda _: next(inputs),
            print_fn=lambda *a, **k: None,
        )

        async def _mock_validate(token):
            return (True, {"username": "Bot", "id": "1"})

        with patch("src.setup_wizard.validate_discord_token", _mock_validate):
            with patch("src.setup_wizard.detect_systemd", return_value=False):
                wizard.run()

        mode = env_path.stat().st_mode & 0o777
        assert mode == 0o600

    def test_wizard_config_yaml_round_trips(self, tmp_path):
        """Wizard-generated config.yml survives YAML round-trip."""
        config_path = tmp_path / "config.yml"
        env_path = tmp_path / ".env"

        inputs = iter([
            "MTIz.NDU2.Nzg5",
            "n", "n", "n", "n", "n", "n", "",
        ])

        wizard = SetupWizard(
            config_path=config_path,
            env_path=env_path,
            input_fn=lambda _: next(inputs),
            print_fn=lambda *a, **k: None,
        )

        async def _mock_validate(token):
            return (True, {"username": "Bot", "id": "1"})

        with patch("src.setup_wizard.validate_discord_token", _mock_validate):
            with patch("src.setup_wizard.detect_systemd", return_value=False):
                wizard.run()

        original = yaml.safe_load(config_path.read_text())
        dumped = yaml.dump(original)
        restored = yaml.safe_load(dumped)
        assert restored["discord"]["token"] == original["discord"]["token"]
        assert restored["tools"]["hosts"] == original["tools"]["hosts"]

    def test_setup_not_needed_after_wizard_completes(self, tmp_path):
        """After wizard writes files, is_setup_needed returns False."""
        config_path = tmp_path / "config.yml"
        env_path = tmp_path / ".env"

        inputs = iter([
            "MTIz.NDU2.Nzg5",
            "n", "n", "n", "n", "n", "n", "",
        ])

        wizard = SetupWizard(
            config_path=config_path,
            env_path=env_path,
            input_fn=lambda _: next(inputs),
            print_fn=lambda *a, **k: None,
        )

        async def _mock_validate(token):
            return (True, {"username": "Bot", "id": "1"})

        with patch("src.setup_wizard.validate_discord_token", _mock_validate):
            with patch("src.setup_wizard.detect_systemd", return_value=False):
                wizard.run()

        # After wizard writes real token, setup should no longer be needed
        assert is_setup_needed(config_path, env_path) is False


# ===================================================================
# Cross-round: All validation functions pass on real files
# ===================================================================


class TestAllValidatorsPassOnRealFiles:
    """Meta-test: run ALL validators on ALL real packaging files."""

    def test_service_file_valid(self):
        content = (PACKAGING_DIR / "heimdall.service").read_text()
        errors = validate_service_file(content)
        assert errors == [], f"Service file errors: {errors}"

    def test_postinstall_valid(self):
        content = (PACKAGING_DIR / "postinstall.sh").read_text()
        errors = validate_postinstall(content)
        assert errors == [], f"Postinstall errors: {errors}"

    def test_preremove_valid(self):
        content = (PACKAGING_DIR / "preremove.sh").read_text()
        errors = validate_preremove(content)
        assert errors == [], f"Preremove errors: {errors}"

    def test_nfpm_config_valid(self):
        content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(content)
        errors = validate_nfpm_config(config)
        assert errors == [], f"nfpm config errors: {errors}"

    def test_nfpm_file_references_valid(self):
        content = (PACKAGING_DIR / "nfpm.yml").read_text()
        config = parse_nfpm_config(content)
        errors = validate_nfpm_file_references(config, PACKAGING_DIR)
        assert errors == [], f"nfpm file reference errors: {errors}"

    def test_release_workflow_valid(self):
        content = (WORKFLOWS_DIR / "release.yml").read_text()
        config = parse_workflow(content)
        errors = validate_release_workflow(config)
        assert errors == [], f"Workflow errors: {errors}"

    def test_release_workflow_actions_valid(self):
        content = (WORKFLOWS_DIR / "release.yml").read_text()
        config = parse_workflow(content)
        errors = validate_workflow_actions(config)
        assert errors == [], f"Workflow action errors: {errors}"


# ===================================================================
# Token format validation consistency
# ===================================================================


class TestTokenValidationConsistency:
    """Verify token validation is consistent between CLI and web wizard."""

    def test_valid_token_accepted_by_validator(self):
        """Standard Discord token format accepted."""
        assert validate_token_format("MTIz.abc.def") is True

    def test_invalid_token_rejected_by_validator(self):
        """Invalid format rejected."""
        assert validate_token_format("not-a-token") is False
        assert validate_token_format("") is False
        assert validate_token_format("a.b") is False
        assert validate_token_format("a..c") is False

    def test_placeholder_token_has_wrong_format(self):
        """The placeholder token does NOT pass format validation."""
        from src.setup_wizard import PLACEHOLDER_TOKEN
        # The placeholder is 'your-discord-bot-token-here' which has
        # dashes but not dots — it should fail format validation
        assert validate_token_format(PLACEHOLDER_TOKEN) is False


# ===================================================================
# Default config template immutability
# ===================================================================


class TestDefaultConfigImmutability:
    """Verify _DEFAULT_CONFIG is not mutated by build_config calls."""

    def test_repeated_calls_independent(self):
        """Multiple build_config calls don't interfere with each other."""
        cfg1 = build_config(
            hosts={"a": {"address": "1.2.3.4"}},
            features={"browser": True},
            web_api_token="token1",
        )
        cfg2 = build_config(
            hosts={"b": {"address": "5.6.7.8"}},
            features={"voice": True},
            web_api_token="token2",
        )

        # Verify independence
        assert "a" in cfg1["tools"]["hosts"]
        assert "b" not in cfg1["tools"]["hosts"]
        assert "b" in cfg2["tools"]["hosts"]
        assert "a" not in cfg2["tools"]["hosts"]

        assert cfg1["browser"]["enabled"] is True
        assert cfg2["browser"]["enabled"] is False
        assert cfg2["voice"]["enabled"] is True
        assert cfg1["voice"]["enabled"] is False

    def test_default_config_unchanged_after_build(self):
        """_DEFAULT_CONFIG is unchanged after build_config calls."""
        original_hosts = copy.deepcopy(_DEFAULT_CONFIG["tools"]["hosts"])
        original_browser = _DEFAULT_CONFIG["browser"]["enabled"]

        build_config(
            hosts={"x": {"address": "10.0.0.1"}},
            features={"browser": True},
        )

        assert _DEFAULT_CONFIG["tools"]["hosts"] == original_hosts
        assert _DEFAULT_CONFIG["browser"]["enabled"] == original_browser
